### ISSUE TITLE
Generate NOTICE file for ClearlyDefined from ClearlyNoticed

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/clearlydefined#100]
NOTICE file here: https://github.com/clearlydefined/clearlydefined/blob/master/docs/legal/NOTICES.md

Should be an output from our package-lock.json that's been generated by ClearlyNoticed.

@dabutvin for visibility

**Comment by darshank15** [comment]
hi @fossygirl ,

Can you give me some more details on this issue?

**Comment by fossygirl** [comment]
@darshank15 We have the ability to generate NOTICE files with ClearlyNoticed if you have a package-lock file for the project. As the issue says, it would be good for us to generate our own NOTICE file for ClearlyDefined from ClearlyNoticed. The document that's currently linked at the page above is not generated using ClearlyNoticed.

**Comment by sbs2001** [comment]
@fossygirl  I've implemented the ClearlyNoticed github action for my fork of https://github.com/clearlydefined/website at https://github.com/sbs2001/website 

Upon changes in the lock  file the bot files in PR like https://github.com/sbs2001/website/pull/1

I've used https://github.com/dabutvin/chive-action

I want to know which repo you want clearlynoticed setted up as this repo has no lock file. Did you meant the clearlydefined website repo ? 

Also the PR template is customizable please give me the PR's template.

**Comment by nickvidal** [comment]
Notices are available [here](https://docs.clearlydefined.io/docs/legal/NOTICES) now. Not sure how this gets updated, but closing this for now.
