### ISSUE TITLE
Automatically flag a percentage of components for manual verification

### ISSUE THREAD

**Issue by iamwillbar** [clearlydefined/clearlydefined#104]
We should regularly flag a percentage of component for manual verification as a QA step to identify places where we could have done better detection or summarization.

For example, we could have a #qualitycheck channel in Discord that the system randomly posts harvested components to for us to manually check and discuss.

**Comment by nickvidal** [comment]
Thanks @iamwillbar for the suggestion. This is a good idea, but given how old this issue is, I'm closing it for now. If anyone wants to pick this up, feel free to open it again.
