### ISSUE TITLE
Harvest vcpkg

### ISSUE THREAD

**Issue by ignacionr** [clearlydefined/clearlydefined#117]
vcpkg is a Microsoft package manager aimed at C++. It has a repository with CMake scripts that point to package sources and means to building them.

In many cases packages will come from GitHub, but they can also have other means of downloading, such as pointing to an arbitrary tarball on some http url.

An example could be https://github.com/microsoft/vcpkg/blob/master/ports/libgeotiff/portfile.cmake which seems valuable since we don’t yet feature LibGeoTiff but appears as a dependency of at least one other package.

**Comment by jeffmendoza** [comment]
Looking for input.

**Comment by nickvidal** [comment]
Thanks @ignacionr and @jeffmendoza. Given how old this issue is, I'm closing it for now. If anyone wants to pick this up, feel free to open it again.
