### ISSUE TITLE
Add crawler support for pagure.io

### ISSUE THREAD

**Issue by richardfontana** [clearlydefined/clearlydefined#118]
I am still pretty unfamiliar with ClearlyDefined so I hope this issue makes sense. [Pagure.io](https://pagure.io) is a hosted instance of pagure, an open source git-based source code hosting system associated with the Fedora Project, currently hosting over a thousand projects, some of which (admittedly not a *huge* number) are ultimately packaged commercially in Red Hat products.

**Comment by nickvidal** [comment]
Given that this issue has been transferred, I'm closing it.
