### ISSUE TITLE
Support URLs and slashes in coordinates

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/clearlydefined#119]
@jeffmcaffer and I had some discussions with people knowledgeable in Go about supporting it. We came around to a problem: the ClearlyDefined coordinate slashes that delineate between type, provider, namespace, name, and revision are load-bearing. 

Go integration will require supporting a URL (Go calls them "import paths") as part of the construction of the ClearlyDefined coordinates.

Import paths are defined such that they can contain any unicode character.  The spec does also mention:

> A compiler may restrict ImportPaths to non-empty strings using only characters belonging to Unicode's L, M, N, P, and S general categories (the Graphic characters without spaces) and may also exclude the characters !"#$%&'()*,:;<=>?[\]^`{|} and the Unicode replacement character U+FFFD.

I don't know if the main go compiler excludes any of those characters in practice, such that we could simply replace "/" with ":", for example.

@rspier for visibility

**Comment by nellshamrell** [comment]
We have found a way around this by using url encoding for Go components, as laid out in [this architecture doc](https://github.com/clearlydefined/service/blob/f46825be91a40157696ae36e718172f5cb20248a/docs/architecture/go_components.md)

Note - we are still working on implementing this.

**Comment by nickvidal** [comment]
I believe this has been solved. Thanks all for contributing.
