### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/clearlydefined#130]
This issue is meant to track the current thinking on the roadmap for ClearlyDefined work. Roadmap items are not necessarily committed to, rather these are areas where work is needed or desired by the community. Feel free to add comments to suggest new topics. For discussion of the individual topics, please use the associated issue.

- [ ] Mirroring https://github.com/clearlydefined/service/issues/386
- [ ] Go coordinate support https://github.com/clearlydefined/service/issues/765

**Comment by nickvidal** [comment]
We now have a roadmap as part of the documentation:

https://docs.clearlydefined.io/docs/resources/roadmap

Any additional items to be included to the roadmap are welcome.
