### ISSUE TITLE
Broken or obsolete link on "Contributing code" web page

### ISSUE THREAD

**Issue by jeremykohn** [clearlydefined/clearlydefined#146]
There's a broken link on https://docs.clearlydefined.io/contributing-code ([GitHub source](https://github.com/clearlydefined/clearlydefined/blob/master/docs/contributing-code.md)), as follows:

> The ongoing work is tracked in a set of [GitHub Project on the ClearlyDefined org](https://github.com/clearlydefined/projects). Typically there will be a project for the current monthly milstone. In addition, each repo has a set of GitHub issues and typically several with _Help wanted_ or _Good first issue_ labels. Also look in the repos for a higher level view of the problem areas and a roadmap for where that repo's function is going.

"GitHub Project on the ClearlyDefined org" links to https://github.com/clearlydefined/projects which leads to a 404 page.

Should the URL be updated to https://github.com/clearlydefined in the docs? If so, I'd be glad to send a PR.

**Comment by capfei** [comment]
I think it is suppose to go to https://github.com/orgs/clearlydefined/projects. I submitted a PR to fix it. Thanks for pointing it out!
