### ISSUE TITLE
Accept-Version not required and may cause problems?

### ISSUE THREAD

**Issue by dangoor** [clearlydefined/clearlydefined#155]
[This page](https://docs.clearlydefined.io/using-data) says the following:

> To use the API, `Accept-Version: 1.0.0` must be added to the headers.

I had some code that added this header to a `GET` request and it worked fine. I switched over to using a `POST` request and started getting a 404 response that cleared up when I removed this header.

So it appears that this header isn't actually required _and_ even causes things to fail when doing a `POST`. I'm not sure if a doc change or a code change is better here.

**Comment by dangoor** [comment]
I've made a [PR to update the docs](https://github.com/clearlydefined/clearlydefined/pull/158) referencing this issue.

**Comment by nickvidal** [comment]
Closed by #184, thanks again @dangoor
