### ISSUE TITLE
Separation of code licenses and documentation licenses

### ISSUE THREAD

**Issue by ajhenry** [clearlydefined/clearlydefined#159]
The `opencontainers` and `docker` projects are governed by different licenses for their code and documentation. 

For the following project: https://github.com/opencontainers/go-digest

The project contains two license files:
[LICENSE](https://github.com/opencontainers/go-digest/blob/master/LICENSE)
[LICENSE.docs](https://github.com/opencontainers/go-digest/blob/master/LICENSE.docs)

Where the `LICENSE` file is Apache-2.0 and applies to the code and `LICENSE.docs` is CC-BY-SA-4.0 and applies to the README and CONTRIBUTING files.

However, when we access this package's entry in ClearlyDefined the declared field is listed as `Apache-2.0 AND CC-BY-SA-4.0`
https://clearlydefined.io/definitions/go/golang/github.com%2Fopencontainers/go-digest/v1.0.0

It would be useful for CD to list out a separate field for documentation licenses.

**Comment by nickvidal** [comment]
I'm closing issues older than a year, but feel free to reopen if still interested.
