### ISSUE TITLE
Support multi-version curations

### ISSUE THREAD

**Issue by mpcen** [clearlydefined/clearlydefined#164]
Opening up a discussion around support for multi-version curation.

I know there were talks and work done in the past to support this but I believe the feature may have been turned off because too many PR's were getting opened.

@capfei @ariel11 to confirm.

**Comment by capfei** [comment]
I'll have to dig through some of the older PRs and emails to remember other issues but one problem I do remember is that it was submitting PRs for versions that didn't need it. The scanners already had detected the correct license.

Example PR:
https://github.com/clearlydefined/curated-data/pull/11738

I _*think*_ it was also submitting license curations based on the previous curation without any consideration for the versions before and after and not checking if the license information had changed (like the license URLs or package metadata).

**Comment by nickvidal** [comment]
I'm closing issues older than a year, but feel free to reopen if still interested.
