### ISSUE TITLE
Architecture Query

### ISSUE THREAD

**Issue by lamarrr** [clearlydefined/clearlydefined#167]
I was wondering if you could point me to a documentation or explanation of the architecture, I'm about to add conda support and having difficulties navigating through the code.

**Comment by nickvidal** [comment]
@lamarrr thanks for adding [conda support](https://github.com/clearlydefined/website/pull/1028)! Closing this for now, but anything that could enhance the documentation would be very much appreciated, and we should also write a blog post about conda.
