### ISSUE TITLE
Create mission/vision/philosophy statement for charter

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/clearlydefined#25]
The charter talks quite a bit about governance and technology process, but doesn't have a lot of information about the intention and philosophy behind the project. We've gotten feedback it would be good to add a mission, vision, or statement of philosophy to the charter so that it's clear later as the project gets bigger.

**Comment by nickvidal** [comment]
The charter is now available [here](https://docs.clearlydefined.io/docs/community/charter), but we might need to create a history/background page to talk about the intention and philosophy behind the project. Closing this for now, but happy to receive any PRs.
