### ISSUE TITLE
"Best practices" or other "happy path" doc

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/clearlydefined#28]
We do not want to be prescriptive to the users about how they have to use ClearlyDefined in any way. However, it would be helpful to outline the way ClearlyDefined could fit into the broader ecosystem and what a "happy path" set up might look like. To explore later.

**Comment by nickvidal** [comment]
Agreed @fossygirl. This will be an ongoing work. Closing the issue for now. Any PRs that address this issue are welcome!
