### ISSUE TITLE
Write, review, and practice OSLS presentation

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/clearlydefined#29]
We were accepted for the OSLS to give our announcement talk for ClearlyDefined. Now we need to actually make the presentation, review it, and practice giving it. 

Here's the current presentation draft, which is taken largely from what Jeff had in December last year: https://docs.google.com/presentation/d/1xSqpjWdARzuXEYKyqNnEl8_ob7AuvYA6PgKoM-KlyI0/edit?usp=drive_web&ouid=106914622056861826817

We also need to make sure the architectural diagrams are up to date for the presentation, related to [#37](https://github.com/clearlydefined/service/issues/37)

@rashmichitrakar @jeffmcaffer

**Comment by rashmichitrakar** [comment]
Deck so far: https://docs.google.com/presentation/d/1xSqpjWdARzuXEYKyqNnEl8_ob7AuvYA6PgKoM-KlyI0/edit#slide=id.g31d6b6fa4b_2_45

**Comment by fossygirl** [comment]
I'm going to close this, but @rashmichitrakar will get @jeffmcaffer and I times for a Tuesday afternoon presentation review offline. Otherwise this is done.
