### ISSUE TITLE
change docs font to montserrat

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/clearlydefined#39]
need to update the jekyll templates etc. and up the size just  touch

**Comment by kpfleming** [comment]
Please assign to me and I'll address it this week.

**Comment by chryw** [comment]
@jeffmcaffer Sorry I forgot to mention that we proposed to use Montserrat font for branding assets, not the actual reading content. I would use a common font like [Open Sans](https://fonts.google.com/specimen/Open+Sans) or just sans-serif. I'll defer to the web design team. Thanks!
![image](https://user-images.githubusercontent.com/7075677/37302507-f6da4640-25e8-11e8-9050-8278dbbcc8f4.png)

**Comment by kpfleming** [comment]
OK, I can revert the wiki/docs site to a different font for body copy, navigation, menus, etc. so that Montserrat is only used for the logo and the tag line below the logo.

**Comment by jeffmcaffer** [comment]
Hmm, we should change the website too. Any preference between open sans and sans-serif?

**Comment by chryw** [comment]
@jeffmcaffer Both are good for long paragraphs. Did the web design team give any font recommendation? If not I personally like Open Sans better :-) 

Open Sans
![image](https://user-images.githubusercontent.com/7075677/37314308-9a81e286-2610-11e8-9268-2383849b2a4a.png)

Sans-serif
![image](https://user-images.githubusercontent.com/7075677/37314239-464ff20c-2610-11e8-8295-f2ce1f910276.png)

**Comment by mynameistechno** [comment]
👍 Open Sans

**Comment by gauntface** [comment]
Please use font-display as well to *not* block on the font for body text `font-display: swap`

**Comment by jeffmcaffer** [comment]
I don't have a particular preference between the two fonts. the PR is looking pretty good. Thanks!

**Comment by gianpaj** [comment]
Should we update the title of this Issue to something like:
> Change docs font to Open Sans 

The `<h3>`'s on the homepage should not be Montserrat font, correct?
https://clearlydefined.io/

**Comment by jeffmcaffer** [comment]
only the word "ClearlyDefined" should be Montserat
