### ISSUE TITLE
add header and footer to docs site

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/clearlydefined#42]
Make a modest attempt to style the docs site as follows

* Header that notionally looks similar (logo on left, ...)
* consider having main doc sections as the headings in the header (but only if that is relatively easy)
* add a link to the main site in the docs header
* footer that looks the same-ish as the full site with the same links
* bound the width of the docs site roughly the same as the main site. Super wide doc is hard to read anyway
* switch to Montserrat font and up the size a bit (see also #39)
* de-bullet the lists in the left nave area

**Comment by kpfleming** [comment]
I can tackle some of this stuff, so assign to me and I'll do what I can.

**Comment by Yehonal** [comment]
Before doing it you should merge my pull request that updated git-wiki to version 2.0

This version introduces a modular architecture via compobents that you can use to build your own layouy resuing git-wiki components.

More info here about costumization tips: http://www.drassil.org/git-wiki/wiki/customize
