### ISSUE TITLE
Discuss upstream contributions from CD with package managers

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/clearlydefined#52]
@pombredanne mentioned it would be a good idea to reach out to the package managers about how to respectfully and tastefully start to work with upstream projects for the ClearlyDefined data once it starts to get curated.

We need the project to move a bit further along and to have more substantial harvested and curated components, but this is something we should keep an eye on and check in about soon.

**Comment by nickvidal** [comment]
Given that this outreach is something that we'll have to constantly address, I'm closing this issue for now.
