### ISSUE TITLE
ClearlyDefined scoring

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/clearlydefined#61]
The ClearlyDefined score is an important part of the philosophy of the project. We want open source projects to understand how they can become more clearly defined, and for that to be a score that they are aware of, drive to get better, and publicize publicly. 

We first want to create the algorithm for how the score is produced and have it well documented how that algorithm is derived and what things projects can do to make it get better. We then want associated tasks around tracking scores and driving communities to be more clearly defined.

**Comment by pombredanne** [comment]
@fossygirl @jeffmcaffer @tsteenbe @rashmichitrakar if you could have a look at the scoring proposal and provide some feedback (either here or as comments on the doc) that would be very nice!

**Comment by fossygirl** [comment]
@pombredanne I'm closing this issue on this repo. If you'd like to open an issue on the license-score repo, please do, otherwise we can call the existence of the repo proof of work on a score. :-)

**Comment by pombredanne** [comment]
For reference, things are now tracked in https://github.com/clearlydefined/license-score
