### ISSUE TITLE
UI: Expanded detail

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/clearlydefined#64]
As a definition list user I am able to expand an individual item and see more detail. I appreciate that the expansion is not so large as to disrupt my list and I can compare multiple expanded items at the same time for example. 

An expanded entry show extra info such as 

* Release date
* Source component (if applicable)
* Declared license
* Facet information
* Discovered licenses
* Discovered copyrights
* Tools used to discover the above information
* Statistics about the definition (e.g., number of files, count of files missing licenses, copyrights, …)

**Comment by jeffmcaffer** [comment]
duplicate
