### ISSUE TITLE
GitHub checks

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/clearlydefined#69]
We think it's likely that adding GitHub checks will give us a richer development experience. We'd like someone to investigate this and then do the implementation of the checks if we all agree that they'll be useful to us. 

https://developer.github.com/v3/checks/
https://blog.github.com/2018-05-07-introducing-checks-api/

**Comment by jeffmcaffer** [comment]
replaced with https://github.com/clearlydefined/service/issues/151 to keep the issues in their respective repos
