### ISSUE TITLE
Write a "how to think about using the data" doc

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/clearlydefined#73]
We want a section that's part of the "use of the data" document https://docs.clearlydefined.io/using-data that talks about how users can _think about_ the data. What is is trying to provide? What won't it provide for them? How much can they rely on it? For what things can they rely on it providing? Is there an SLA? Are there any assurances made? Etc.

**Comment by nickvidal** [comment]
Thank you for your suggestion @fossygirl. I think this is a good idea, but given how old this issue is, I'm closing it for now. If anyone wants to pick this up, feel free to open it again.
