### ISSUE TITLE
Cannot scroll side-menu

### ISSUE THREAD

**Issue by gianpaj** [clearlydefined/clearlydefined#78]
![](https://media.giphy.com/media/1fgJhnbkJVXWW7tYXy/giphy.gif)

Also here's how it looks a on a 15" MacBook retina screen at full height (1756px):

<img width="998" alt="clearlydefined_by_clearlydefined" src="https://user-images.githubusercontent.com/899175/44055292-a6113456-9f4d-11e8-92c7-7c341f648938.png">

**Comment by Yehonal** [comment]
Hi, first of all thanks for using git-wiki project. I've added your doc website to our exaples list: http://www.drassil.org/git-wiki/wiki/examples.html

About this issue, has been fixed here:

https://github.com/Drassil/git-wiki/commit/dd78e1d1b49e7a011bee241d2cb087515640b746

Please if you have issues with theme or any kind of wiki functionalities open an issue on main project and try to keep the core sources updated.

Thanks

**Comment by fossygirl** [comment]
@gianpaj Has this been fixed, or what is the next step here?

**Comment by AlexWebYourmind** [comment]
@fossygirl  Gianpaj is no longer contributing to the project, but as per @Yehonal 's comment, we should just update git-wiki? not sure what's the process to do it, as this means to update the codebase and redeploy it (I don't see any package.json on this repo).

Can you share the process or let us know who is supposed to do it?

**Comment by Yehonal** [comment]
I think you can just merge the master branch of original git-wiki
repository. It should be enough and you can solve code conflicts if any.

Il Gio 25 Ott 2018, 11:49 Alessandro (Alex) Russo <notifications@github.com>
ha scritto:

**Comment by AlexWebYourmind** [comment]
@Yehonal Thanks for the heads up!
