### ISSUE TITLE
Update documentation on how to manage development environments for website project

### ISSUE THREAD

**Issue by storrisi** [clearlydefined/clearlydefined#80]
As mentioned [here](https://github.com/clearlydefined/website/issues/257), development enviroments should be managed in a different way unlike what's happening at this time.
Once the new process has been implemented, the documentation will need to be updated.

**Comment by jeffmcaffer** [comment]
see also https://github.com/clearlydefined/website/pull/222 where we resolve to add doc for how to run tests on Mac wrt how to install `watchman`.

**Comment by storrisi** [comment]
We can close this since is superseeded by #85
