### ISSUE TITLE
Update About Page to reflect current partners

### ISSUE THREAD

**Issue by AlexWebYourmind** [clearlydefined/clearlydefined#84]
AS per discussion with @jeffmcaffer, we should update the about page https://clearlydefined.io/about to reflect current project partners

**Comment by AlexWebYourmind** [comment]
![image](https://user-images.githubusercontent.com/8700407/46417506-b89dd600-c721-11e8-9356-8f3f89597a15.png)
@jeffmcaffer @fossygirl attaching the updated partners list as per Jeff's presentation. Hope that helps!

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer @fossygirl are there any updates on this one?

**Comment by fossygirl** [comment]
@AlexWebYourmind I think just submit an appropriate pull request with your logo and @jeffmcaffer and I will review it?

**Comment by AlexWebYourmind** [comment]
@fossygirl Thanks for your reply.  I discussed this particular requirement with @jeffmcaffer in September, and, at least from my understanding, you were going to take care of it, given you have the full list (and logos) of all the partners?

@jeffmcaffer  has already our logo, but this issue is to be intended as a general about page update which includes all the partners as per the image above? (I have taken that from Jeff's OSI presentation).

These should include CodeScoop, Google and WebYourMind.

If you prefer Us to take ownership on this issue and submit the PR, we can surely do it. @fossygirl can you confirm you want us to do that? Thanks!

**Comment by fossygirl** [comment]
@AlexWebYourmind Okay, I understand. @jeffmcaffer and i haven't discussed this yet, so this may be a while before I have a chance to sync with him.

**Comment by jeffmcaffer** [comment]
Feel free to put in a PR that adds the images to https://github.com/clearlydefined/website/tree/master/src/images/partner-logos and lays them out in https://github.com/clearlydefined/website/blob/master/src/components/PageAbout.js

If you can add the other missing ones that would be great. You may need the original powerpoint for the good images with transparency etc. @fossygirl can likely find that on our internal doc share though the pptx files should find their way to the google docs folder.

**Comment by AlexWebYourmind** [comment]
@jeffmcaffer nad @fossygirl thanks for your reply. I will chase this up. I can also search for high-res company logos online if needed. Will submit a PR in the next few days.

**Comment by AlexWebYourmind** [comment]
Closing this as it will be fixed in https://github.com/clearlydefined/website/issues/353
