### ISSUE TITLE
Refer to CII Best Practices badge

### ISSUE THREAD

**Issue by david-a-wheeler** [clearlydefined/clearlydefined#97]
The Linux Foundation's Core Infrastructure Initiative (CII)'s Best Practices badge lets projects show that they follow best practices, with an emphasis on security-related practices. I'm the lead of the project.  You can see more here:

* Web site: https://bestpractices.coreinfrastructure.org/
* Repo: https://github.com/coreinfrastructure/best-practices-badge

I think it'd be useful to know, for each project, if it's pursuing a badge and what level (in progress, passing, silver, gold).  You mentioned that you were interested in ways to measure projects, especially for security - I think this would be a good start.

You can easily query the database using our [API](https://github.com/coreinfrastructure/best-practices-badge/blob/master/doc/api.md).  For you example, you can get information about the Kubernetes project by querying by name or URL like this:

* https://bestpractices.coreinfrastructure.org/projects.json?pq=https%3A%2F%2Fgithub.com%2Fkubernetes%2Fkubernetes
* https://bestpractices.coreinfrastructure.org/projects.json?pq=Kubernetes

Let me know if you have any questions!

**Comment by nickvidal** [comment]
Thank you for your suggestion @david-a-wheeler. I think this is a really good idea, but given how old this issue is, I'm closing it for now. If anyone wants to pick this up, feel free to open it again.
