### ISSUE TITLE
"Contributing Data" (contributing-data.md) is confusing

### ISSUE THREAD

**Issue by richardfontana** [clearlydefined/clearlydefined#98]
One paragraph in https://docs.clearlydefined.io/contributing-data is confusing for a couple of reasons:

1. It says "Contributing data is done on Curation page of the website." However, the linked [Curation](https://clearlydefined.io/curate) page appears to be just a general overview of ClearlyDefined; it is not a page for curation. 

2. The sentence "You can get there by clicking the Curate this entry button on an entry on the Browse page. " As far as I can tell there is no "Curate this entry button" associated with any entry one can browse on the Browse page. I think this might refer to a set of buttons or similar elements that can be used to curate an entry through the web interface.

**Comment by nickvidal** [comment]
Thanks for the feedback @richardfontana. As part of the documentation overhaul, we plan provide better guidance on contributing data and curation, including screenshots and examples. Since this is a really old issue and your comments might not reflect the current UI, I'm closing this for now.
